### ISSUE TITLE
Links in the formatting readme are not working

### ISSUE THREAD

**Issue by williamhobbs** [sandialabs/pvcracks#6]
Links to notebook files in https://github.com/sandialabs/pvcracks/blob/main/retrain/formatting/README.md just go to the formatting folder. 

E.g.,

https://github.com/sandialabs/pvcracks/blob/09ad7d58d9a6a9f54fb4241eae62451353047229/retrain/formatting/README.md?plain=1#L2

I think all the links are like this.

**Comment by NormanJost** [comment]
Thanks for pointing this out @williamhobbs.
Just did a quick edit to add them:
[Commit 8b54016
](https://github.com/sandialabs/pvcracks/commit/8b54016485843ec74e9ae45e6398481d8f69aca3)
